### ISSUE TITLE
throw 'RangeError: Invalid position 1 in document of length 0' when calling `set` method with JSON value under text mode

### ISSUE THREAD

**Issue by cloydlau** [josdejong/svelte-jsoneditor#381]
Hello jos,
Here is the minimal reproduction: https://github.com/cloydlau/reproduction.git

**Comment by thaneuk** [comment]
A quick work around I'm using is to create it in tree mode; then immediately call `jsonEditor.updateProps({ mode: Mode.text })` to convert it to text.

**Comment by josdejong** [comment]
Fixed now in `v0.21.3`

**Comment by thaneuk** [comment]
I'm still seeing the issue with vanilla-jsoneditor.

"name": "vanilla-jsoneditor"
"version": "0.21.3"

```
new JSONEditor({
  target: element,
  props: {
    readOnly: true,
    mainMenuBar: false,
    navigationBar: false,
    statusBar: false,
    mode: Mode.text
  }
});
```

```
RangeError: Invalid position 1 in document of length 0
    at TextLeaf.lineAt (index.js:10:19)
    at WrappedLineIndent.getVisibleLines (index.js:58:40)
    at WrappedLineIndent.addStyleToBuilder (index.js:40:35)
    at Object.read (index.js:31:30)
    at index.js:7249:34
    at Array.map (<anonymous>)
    at EditorView.measure (index.js:7247:42)
    at index.js:7382:79
```

**Comment by josdejong** [comment]
Thanks for testing with the latest version. I've tried to reproduce your issue but without success so far: 

https://jsbin.com/pufufol/edit?html,output

Can you share more details?

**Comment by thaneuk** [comment]
I added an update to the code and got the error.

```
editor.update({
  json: {}
})
```

```
"RangeError: Invalid position 1 in document of length 0
    at t.value (https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.21.3/standalone.min.js:25:416667)
    at e.value (https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.21.3/standalone.min.js:25:879553)
    at e.value (https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.21.3/standalone.min.js:25:879060)
    at Object.read (https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.21.3/standalone.min.js:25:878894)
    at https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.21.3/standalone.min.js:25:620350
    at Array.map (<anonymous>)
    at e.value (https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.21.3/standalone.min.js:25:620320)
    at https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.21.3/standalone.min.js:25:622924"
```

**Comment by thaneuk** [comment]
I also tested with initial value incase it was using update without an initial value to start but had no luck.

```
<script type="module">
  import { JSONEditor } from 'https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.21.3/standalone.min.js'

  const editor = new JSONEditor({
    target: document.getElementById('jsoneditor'),
    props: {
      readOnly: true,
      mainMenuBar: false,
      navigationBar: false,
      statusBar: false,
      mode: 'text',
      content: { json: {} }
    }
  })

  editor.update({ json : { test: Math.random() } })
</script>
```

**Comment by josdejong** [comment]
Thanks, I'll do further debugging.

**Comment by josdejong** [comment]
As a workaround you can, you can just not call `.update` right after the editor is created (the contents is passed to along the constructor anyway). If you need that right after construction, you can maybe add a `setTimeout(() => { editor.update(...) })` for the time being.

**Comment by thaneuk** [comment]
This is the work around I'm using

https://jsbin.com/desowehibi/1/edit?html,console,output

**Comment by josdejong** [comment]
It looks like the issue originates from the [codemirror-wrapped-line-indent](https://github.com/fauzi9331/codemirror-wrapped-line-indent) extension that we use, I've reported the issue there: https://github.com/fauzi9331/codemirror-wrapped-line-indent/issues/1.

**Comment by josdejong** [comment]
This should be fixed now in `v0.21.4`, can you give it a try @thaneuk ?

**Comment by thaneuk** [comment]
Can confirm, not having the issue now with the latest update.

Many thanks for the attention to this.

**Comment by josdejong** [comment]
Thanks for your feedback, good to hear!
